### ISSUE TITLE
ImportError: There is no such entity as whisper.tokenizer.get_tokenizer

### ISSUE THREAD

**Issue by wanghkkk** [SpenserCai/ComfyUI-FunAudioLLM#12]
when i use the office model like below :

![image](https://github.com/user-attachments/assets/19cd79ce-7bfc-4b73-a36d-bb68986efca2)

the ERROR when run:

!!! Exception during processing !!! There is no such entity as whisper.tokenizer.get_tokenizer
Traceback (most recent call last):
  File "D:\SD\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\SD\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-FunAudioLLM\nodes\cosyvoice_nodes.py", line 72, in generate
    cosyvoice = CosyVoicePlus(model_dir)
  File "D:\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-FunAudioLLM\cosyvoice\cli\cosyvoice.py", line 40, in __init__
    configs = load_hyperpyyaml(f)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\hyperpyyaml\core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ruamel\yaml\constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ruamel\yaml\constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ruamel\yaml\constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ruamel\yaml\constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "D:\SD\ComfyUI-aki-v1.4\python\lib\site-packages\hyperpyyaml\core.py", line 491, in _construct_name
    raise ImportError("There is no such entity as %s" % callable_string)
ImportError: There is no such entity as whisper.tokenizer.get_tokenizer

How can I fix this? thanks

**Comment by thinkluck** [comment]
I also encountered the same problem

**Comment by SpenserCai** [comment]
https://github.com/FunAudioLLM/CosyVoice/issues/251

https://github.com/FunAudioLLM/CosyVoice/issues/203

**Comment by mkat2** [comment]
still not solved, what is final solution?
