### ISSUE TITLE
Unable to install in Windows: Pynini and webrtcvad cannot be built

### ISSUE THREAD

**Issue by Beatboxace** [SpenserCai/ComfyUI-FunAudioLLM#7]
Hi,
Thank you for trying to make this available in ComfyUI!

I am using Windows 11 64 bit and the portable version of ComfyUI installation (which means it's using python_embeded environment).

## Summary
I am afraid in it's current state, it seems to be impossible to install on Windows (at least with comfy portable) because of `pynini` and `webrtcvad` 's build requirements. When opening the test workflow there are missing nodes in red (as reqs weren't able to finish I'm guessing).

## Steps
I followed your instructions to install Conda, then pynini=2.1.5 through the conda-forge.
That part seems to be working, but the following command `pip install -r requirements.txt` result in an error to build pynini:

### Pynini
```
Building wheel for pynini (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-311\pynini
      copying pynini\__init__.py -> build\lib.win-amd64-cpython-311\pynini
      creating build\lib.win-amd64-cpython-311\pywrapfst
      copying pywrapfst\__init__.py -> build\lib.win-amd64-cpython-311\pywrapfst
      creating build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\case.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\chatspeak.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\chatspeak_model.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\dates.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\g2p.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\numbers.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\plurals.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\t9.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\weather.py -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\examples\__init__.py -> build\lib.win-amd64-cpython-311\pynini\examples
      creating build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\export.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\grm.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\grm_example.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\multi_grm.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\multi_grm_example.py -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\export\__init__.py -> build\lib.win-amd64-cpython-311\pynini\export
      creating build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\byte.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\edit_transducer.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\features.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\paradigms.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\pynutil.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\rewrite.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\rule_cascade.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\tagger.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\utf8.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\lib\__init__.py -> build\lib.win-amd64-cpython-311\pynini\lib
      copying pynini\__init__.pyi -> build\lib.win-amd64-cpython-311\pynini
      copying pynini\py.typed -> build\lib.win-amd64-cpython-311\pynini
      copying pywrapfst\__init__.pyi -> build\lib.win-amd64-cpython-311\pywrapfst
      copying pywrapfst\py.typed -> build\lib.win-amd64-cpython-311\pywrapfst
      copying pynini\examples\py.typed -> build\lib.win-amd64-cpython-311\pynini\examples
      copying pynini\export\py.typed -> build\lib.win-amd64-cpython-311\pynini\export
      copying pynini\lib\py.typed -> build\lib.win-amd64-cpython-311\pynini\lib
      running build_ext
      building '_pywrapfst' extension
      creating build\temp.win-amd64-cpython-311\Release\extensions
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\DEV\AI\Stablediffusion\comfyui\ComfyUI_windows_portable\python_embeded\include -IC:\DEV\AI\Stablediffusion\comfyui\ComfyUI_windows_portable\python_embeded\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpextensions/_pywrapfst.cpp /Fobuild\temp.win-amd64-cpython-311\Release\extensions/_pywrapfst.obj -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
      cl : Command line error D8021 : invalid numeric argument '/Wno-register'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
  ```
  
  -> Windows tools for compiling it doesn`t support the `/Wno-register` argument.
  
  When trying to run the command `[comfypath]\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -r requirements.txt` , I get the same error and another similar one but for `webrtcvad`
  
  ### webrtcvad
  As the python_embeded used by Comfyui portable is a bit lighter from what I understand, using  `Python.h` for dev tools is not possible.

```
  Building wheel for webrtcvad (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      C:\DEV\AI\Stablediffusion\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-311
      copying webrtcvad.py -> build\lib.win-amd64-cpython-311
      running build_ext
      building '_webrtcvad' extension
      creating build\temp.win-amd64-cpython-311\Release\cbits
      creating build\temp.win-amd64-cpython-311\Release\cbits\webrtc\common_audio\signal_processing
      creating build\temp.win-amd64-cpython-311\Release\cbits\webrtc\common_audio\vad
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D_WIN32 -Icbits -IC:\DEV\AI\Stablediffusion\comfyui\ComfyUI_windows_portable\python_embeded\include -IC:\DEV\AI\Stablediffusion\comfyui\ComfyUI_windows_portable\python_embeded\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tccbits\pywebrtcvad.c /Fobuild\temp.win-amd64-cpython-311\Release\cbits\pywebrtcvad.obj
      pywebrtcvad.c
      cbits\pywebrtcvad.c(1): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

I tried installing the wheel directly but was only able to find `webrtcvad_wheels-2.0.14-pp310-pypy310_pp73-win_amd64.whl` which isn't the same as the `webrtcvad-2.0.14-pp310-pypy310_pp73-win_amd64.whl` (non wheels package), because running `pip show webrtcvad` doesn't list it. I was unable to find the "non-wheel" version.
      
### Other informations
While investigating, I found that the dependencies are a bit of a mess. For example, there is `WeTextProcessing` in the `requirements.txt`. When checking that librairie's [dependencies](https://github.com/wenet-e2e/WeTextProcessing/blob/master/requirements.txt), it looks like it forces a more recent version of `pynini` which is different than the one from your README. I also had trouble with `aliyun-python-sdk-core` , which only version `2.13.10` seemed to be the latest compatible. This might not be the main source of the problem tho.

When using comfy manager, there is also 2 registered custom nodes with the same name (both have the IMPORT FAILED error as the setup cannot complete)

## Questions
* Tried a lot of different things to get it to build without success. Installing on Windows seems to be quite a challenge. Were you able to install on Windows with this latest version? Any pointers?
* I tried both and didn't work, but isn't running the command `conda activate` required before trying to install requirements? I feel like there is something missing that kind of _tells_ pip install to use pynini from the conda's installation instead of trying to rebuild,

Using WSL is not an option for me now, as everything else from ComfyUI is already setup and working well. Any help would be appreciated. Thanks!

**Comment by SpenserCai** [comment]
Thank you very much for your valuable suggestions. The dependency issue you mentioned does exist. I have updated the version of pynini to 2.1.6 in readme, and perhaps it can be installed using conda. I don't have a Windows computer, so it's difficult for me to conduct tests. I always refer to the official documentation of CosyVoice to write the README for compatibility issues on Windows.
Btw,i think ```conda activate``` is required,may be you can create a Comfyui environment in conda.

**Comment by Pythonpa** [comment]
Ah, the same,if you installed on windows,this mistake will be repeated.
However, this has nothing to do with the author's project, but is the problem of `pynini` itself. I saw that some people also mentioned such errors in `pynini's` official issues

**Comment by SpenserCai** [comment]
> Ah, the same,if you installed on windows,this mistake will be repeated. However, this has nothing to do with the author's project, but is the problem of `pynini` itself. I saw that some people also mentioned such errors in `pynini's` official issues

Thank you for your understanding. The official solution provided by CosyVoice is to use conda for deployment, which can solve the problem of Windows.

**Comment by Hbolake** [comment]
How long is the approximate generation time? At fifty percent, it is no longer loading.

**Comment by Beatboxace** [comment]
As a note, I was already using Conda but it wasn't working as is by just following the two steps.

After a few hours of investigation and trial/error, I managed to find an alternative method to make it work.

## The problem
When using the portable version of ComfyUI, it uses a "python_embeded" environment that is segmented from the rest of the machine (to avoid side effects of other installations and make it self contained). That env cannot compile `pynini` by itself, as some compilation flags are unsupported on windows dev tools and it lacks some .h files too I think. That python environment is not able to use conda's installations "as-is", at least for me (Comfy does not activate conda's env either).

## Informations & Investigation
If you are curious or if it can help someone, here are infos discovered and used in the solution:
<details>
After installing pynini through conda, It still refused to load within the python_embeded env needed for comfyui.
I used this command to make testing easier than restarting comfyUI each time:
`[Your path]\ComfyUI_windows_portable\python_embeded\python.exe" -c "import pynini; print(pynini.__version__)"`

That essentially use the `--init__.py` located in the installed library's folder `[...]\python_embeded\Lib\site-packages\pynini`
The general idea was to use conda to compile pynini properly, and then manually copy the compiled requirements to the python_embeded env.

The initial specific error was something like this:
```
from _pynini import *
ImportError: DLL load failed while importing _pynini: The specified module could not be found.
```
Pynini is not installed directly by itself, but is required by some dependencies for this project (funasr mainly I think).

So DLLs are missing. But in fact, the DLL missing are from sub dependencies of pynini.
Looking at the [setup.py](https://github.com/kylebgorman/pynini/blob/master/setup.py), there is two extensions declared: `pynini` and `pywrapfst`.

When installing via conda, the library is located in `[...]\miniconda3\Lib\site-packages`, but the dynamic link library needed (.pyd) are located in another folder, in `[...]\miniconda3\pkgs\pynini-...`

So I copied `_pynini.cp311-win_amd64.pyd` and `_pywrapfst.cp311-win_amd64.pyd` to the `[Your path]\ComfyUI_windows_portable\python_embeded\Lib\site-packages` folder.

Modifying the `__init__.py` with some error handling/print feedback can help, something like this:
```
# Now try importing _pynini
try:
    from _pynini import *
    print("Successfully imported _pynini.")
except Exception as e:
    print(f"Failed to import _pynini. Error: {e}")
```

Running the test command again, i had hopes annnnnndddd.... Nope.
I got errors similar to this: `Error: DLL load failed while importing _pynini: The specified module could not be found.`

Alright then. To know which DLL are needed by those two, I looked them up using tools like:
* dumpbin for .pyd, through the Visual Studio Developer Command prompt, ex: `dumpbin /dependents _pynini.pyd`
* [Dependencies](https://github.com/lucasg/Dependencies) and opening the dlls found to see what other dll are needed.

I'll skip some details here but these are needed:
```
fstmpdtscript.dll
fstpdtscript.dll
fstscript.dll
fst.dll
dl.dll
```
As well as some base stuff that you should aready have (via visual studio build tools, python and other basic windows stuff)
```
python311.dll
MSVCP140.dll
KERNEL32.dll
VCRUNTIME140_1.dll
VCRUNTIME140.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
```

So the last step would be to grab the 5 dll listed above generated from conda's build bin repository from `[...]\miniconda3\Library\bin` and drop them in the python env `...\ComfyUI_windows_portable\python_embeded`

Annndd.... Voilà! After a Comfy Server restart it worked!

You might need to install the rest of the dependencies using `--no-deps` param so it doesn't try to rebuild it.

Note: This might be solved by adding some system path var at the right places (ex: for conda's folders used above) in the right order, but that sometimes have other undesired side effects (ex: loading python libraries from elsewhere when you want it to be selfcontained), so I decided not to opt for that. Would need testing to see if it is viable for some.
</details>

## Solution
The solution I used is basically to let conda compile/build, and transfer proper files needed to the python_embeded.
- Install [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html)
- Activate conda env: `conda activate` for default
- Install pynini from conda-forge: `conda install -c conda-forge pynini=2.1.6`
- Manually copy generated files:
-- From `[...]\miniconda3\pkgs\pynini-...`, copy `_pynini.cp311-win_amd64.pyd` and `_pywrapfst.cp311-win_amd64.pyd` to the `[...]\ComfyUI_windows_portable\python_embeded\Lib\site-packages` folder.
-- From `[...]\miniconda3\Library\bin`, copy `fstmpdtscript.dll`, `fstpdtscript.dll`, `fstscript.dll`, `fst.dll`, `dl.dll` to the same location as python exec in `[...]\ComfyUI_windows_portable\python_embeded\Lib\site-packages`
- In a new prompt outside of conda's env, navigate to this custom node folder `custom_nodes\ComfyUI-FunAudioLLM` and install other requirements if not already done using the proper python exec, ex:  `...\ComfyUI_windows_portable\python_embeded\python.exe" -m pip installpip install --no-deps -r requirements.txt`
- Restart ComfyUI's server. Should work!

## Next steps
If you have any alternative other than a manual copy step like that for the setup, don't hesitate to suggest!

-> I could make a pull request to complement your readme with a summary of these steps for people running portable comfy on windows. What do you think :)?

**Comment by Beatboxace** [comment]
> How long is the approximate generation time? At fifty percent, it is no longer loading.

This is unrelated to the current issue, but from my initial tests generating a paragraph is about 30 seconds (16s/iteration), using a 4070 12gb vram (not even sure it fully runs on the GPU).

When generating longer segments I got some glitches and repeating segments as it tries to concatenate, but this might be a seperate issue. Might be a clue as to why it's stuck in the middle.

**Comment by Gue-e** [comment]
windows使用conda命令好像可以：conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing==1.0.3

**Comment by Beatboxace** [comment]
> 使用conda命令好像可以

Are you using the portable version of comfyUI? Windows 11 or Windows 10?

**Comment by rex657** [comment]
@Beatboxace Hi there, Thanks for sharing all the detailed Debug and investigation steps! Those are super useful. But I followed the steps and I am getting a new error. 

Could you please advise if any dll needs to be placed alongside with the 5 dlls you mentioned?
I used the same `dumpbin /dependents .\_pywrapfst.cp311-win_amd64.pyd` and identified below dlls:
  Image has the following dependencies:

    fstfarscript.dll
    fstscript.dll
    fst.dll
    python311.dll
    MSVCP140.dll
    KERNEL32.dll
    VCRUNTIME140_1.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll

I already added the fstfarscript.dll into `ComfyUI_windows_portable\python_embeded\Lib\site-package`, that still gets me this error of
`
  File "G:\ComfyUI\python_embeded\Lib\site-packages\tn\chinese\normalizer.py", line 15, in <module>
    from tn.processor import Processor
  File "G:\ComfyUI\python_embeded\Lib\site-packages\tn\processor.py", line 21, in <module>
    from pynini import (cdrewrite, cross, difference, escape, Fst, shortestpath,
  File "G:\ComfyUI\python_embeded\Lib\site-packages\pynini\__init__.py", line 3, in <module>
    from _pynini import *
  File "extensions\\_pynini.pyx", line 1, in init _pynini
ImportError: DLL load failed while importing _pywrapfst:
`
I am trying to copy the rest of the dlls to the path `ComfyUI_windows_portable\python_embeded\Lib\site-package`, but would be appreciated if I can have your insights too.

Thanks!

**Comment by rex657** [comment]
> @Beatboxace Hi there, Thanks for sharing all the detailed Debug and investigation steps! Those are super useful. But I followed the steps and I am getting a new error.
> 
> Could you please advise if any dll needs to be placed alongside with the 5 dlls you mentioned? I used the same `dumpbin /dependents .\_pywrapfst.cp311-win_amd64.pyd` and identified below dlls: Image has the following dependencies:
> 
> ```
> fstfarscript.dll
> fstscript.dll
> fst.dll
> python311.dll
> MSVCP140.dll
> KERNEL32.dll
> VCRUNTIME140_1.dll
> VCRUNTIME140.dll
> api-ms-win-crt-stdio-l1-1-0.dll
> api-ms-win-crt-heap-l1-1-0.dll
> api-ms-win-crt-filesystem-l1-1-0.dll
> api-ms-win-crt-runtime-l1-1-0.dll
> ```
> 
> I already added the fstfarscript.dll into `ComfyUI_windows_portable\python_embeded\Lib\site-package`, that still gets me this error of `File "G:\ComfyUI\python_embeded\Lib\site-packages\tn\chinese\normalizer.py", line 15, in <module> from tn.processor import Processor File "G:\ComfyUI\python_embeded\Lib\site-packages\tn\processor.py", line 21, in <module> from pynini import (cdrewrite, cross, difference, escape, Fst, shortestpath, File "G:\ComfyUI\python_embeded\Lib\site-packages\pynini\__init__.py", line 3, in <module> from _pynini import * File "extensions\\_pynini.pyx", line 1, in init _pynini ImportError: DLL load failed while importing _pywrapfst:` I am trying to copy the rest of the dlls to the path `ComfyUI_windows_portable\python_embeded\Lib\site-package`, but would be appreciated if I can have your insights too.
> 
> Thanks!

Well, I managed to find the missing piece, except for the steps as highlighted by BeatBoxace
-- From [...]\miniconda3\Library\bin, copy fstmpdtscript.dll, fstpdtscript.dll, fstscript.dll, fst.dll, dl.dll to the same location as python exec in [...]\ComfyUI_windows_portable\python_embeded\Lib\site-packages

We will need 2 additional dll for pywrapfst, which makes it to:
-- From [...]\miniconda3\Library\bin, copy fstmpdtscript.dll, fstpdtscript.dll, fstscript.dll, fst.dll, dl.dll, ***fstfar.dll, fstfarscript.dll*** to the same location as python exec in [...]\ComfyUI_windows_portable\python_embeded\Lib\site-packages

**Comment by Ccccx** [comment]
> windows使用conda命令好像可以：conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing==1.0.3

Mac OS and this command works for me

**Comment by lxmugen** [comment]
OS:windwos10
copy all of the requite dll files to the folder,nonsense.


Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2073, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM\__init__.py", line 9, in <module>
    from .nodes.cosyvoice_nodes import *
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM\nodes\cosyvoice_nodes.py", line 15, in <module>
    from funaudio_utils.cosyvoice_plus import CosyVoicePlus
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM\funaudio_utils\cosyvoice_plus.py", line 9, in <module>
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM\cosyvoice\cli\cosyvoice.py", line 27, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM\cosyvoice\cli\frontend.py", line 30, in <module>
    from tn.chinese.normalizer import Normalizer as ZhNormalizer
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tn\chinese\normalizer.py", line 15, in <module>
    from tn.processor import Processor
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tn\processor.py", line 21, in <module>
    from pynini import (cdrewrite, cross, difference, escape, Fst, shortestpath,
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pynini\__init__.py", line 3, in <module>
    from _pynini import *
  File "extensions\\_pynini.pyx", line 1, in init _pynini
ImportError: DLL load failed while importing _pywrapfst: 找不到指定的模块。

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM module for custom nodes: DLL load failed while importing _pywrapfst: 找不到指定的模块。

**Comment by zslefour** [comment]
> OS:windwos10 copy all of the requite dll files to the folder,nonsense.
> 
> Traceback (most recent call last): File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2073, in load_custom_node module_spec.loader.exec_module(module) File "", line 995, in exec_module File "", line 488, in _call_with_frames_removed File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM__init__.py", line 9, in from .nodes.cosyvoice_nodes import * File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM\nodes\cosyvoice_nodes.py", line 15, in from funaudio_utils.cosyvoice_plus import CosyVoicePlus File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM\funaudio_utils\cosyvoice_plus.py", line 9, in from cosyvoice.cli.cosyvoice import CosyVoice File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM\cosyvoice\cli\cosyvoice.py", line 27, in from cosyvoice.cli.frontend import CosyVoiceFrontEnd File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM\cosyvoice\cli\frontend.py", line 30, in from tn.chinese.normalizer import Normalizer as ZhNormalizer File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tn\chinese\normalizer.py", line 15, in from tn.processor import Processor File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tn\processor.py", line 21, in from pynini import (cdrewrite, cross, difference, escape, Fst, shortestpath, File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pynini__init__.py", line 3, in from _pynini import * File "extensions\_pynini.pyx", line 1, in init _pynini ImportError: DLL load failed while importing _pywrapfst: 找不到指定的模块。
> 
> Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FunAudioLLM module for custom nodes: DLL load failed while importing _pywrapfst: 找不到指定的模块。

一样的错误

**Comment by henrikvilhelmberglund** [comment]
I had the same issue with `load failed while importing _pywrapfst:`

I needed this - https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
